# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87dc2b339f6973466d0038069c1c529808995805aa66f6aeb7b913b6ed61812a531823c782a06999f4bc756c3ac2d8402abf07a3ae7141e5200a4b445d3962a5

test:
  secret_key_base: 912c4d3f4e5ec634f25ccd0b6993cf82fe66e66139490432e58c13b1b1167b2c5e36f7b44ad35701ad8cdebcd8ce810ad85eccfe34653cdbb8a184fa93cef6a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
